### ISSUE TITLE
Set up standardized settings

### ISSUE THREAD

**Issue by Mast3rwaf1z** [aau-p9s/Autoscaler#89]
We have multiple repos across multiple languages that are configured in different ways.

I suggest that we set these in a more standardized way (e.g. environment variables) that will also be easy to set in either docker-compose or kubernetes yaml.

example:
```yaml
service:
  autoscaler:
    image: autoscaler
    environment:
      - AUTOSCALER_PORT: 8080
      - AUTOSCALER_KUBERNETES_ADDR: http://kubernetes
      - AUTOSCALER_PGSQL_HOST: http://pgsql
      - AUTOSCALER_PGSQL_PORT: 5432
      - AUTOSCALER_PGSQL_DB: autoscaler
      - AUTOSCALER_PGSQL_USER: root

```
